sudo nano systemctl start mcreset01
sudo nano systemctl start mcreset02
sudo nano systemctl start mcreset03
sudo nano systemctl start mcreset04
sudo nano systemctl start mcreset05
sudo nano systemctl start mcreset06
sudo nano systemctl start mcreset07
sudo nano systemctl start mcreset08
sudo nano systemctl start mcreset09
sudo nano systemctl start mcreset10
